 <img src="Numpyjpeg1.jpg" align="center" width="300" />

<hr>
<hr style="height:2px;border-width:0;">

### `Welcome to Numpy`

NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

### <em> Uz: Numpyga xush kelibsiz...</em>
<em>NumPy (Numerical Python) - bu fan va muhandislikning deyarli barcha sohalarida qo'llaniladigan ochiq manba Python kutubxonasi. Bu Python-da raqamli ma'lumotlar bilan ishlash uchun universal standart bo'lib, Python va PyData ilmiy ekotizimlarining asosini tashkil etadi. NumPy foydalanuvchilari boshlang'ich kodlovchilardan tortib, eng zamonaviy ilmiy va sanoat tadqiqotlari va ishlanmalari bilan shug'ullanuvchi tajribali tadqiqotchilargacha bo'lgan barchani o'z ichiga oladi. NumPy API Pandas, SciPy, Matplotlib, scikit-learn, scikit-image va boshqa ko'plab ma'lumotlar fanlari va ilmiy Python paketlarida keng qo'llaniladi.

NumPy kutubxonasi ko'p o'lchovli massiv va matritsa ma'lumotlar tuzilmalarini o'z ichiga oladi (bu haqda keyingi bo'limlarda ko'proq ma'lumot topasiz). U bir hil n o'lchovli massiv ob'ekti bo'lgan ndarrayni samarali ishlash usullari bilan ta'minlaydi. NumPy dan massivlarda turli xil matematik amallarni bajarish uchun foydalanish mumkin. U Python-ga massivlar va matritsalar bilan samarali hisob-kitoblarni kafolatlaydigan kuchli ma'lumotlar tuzilmalarini qo'shadi va bu massivlar va matritsalarda ishlaydigan yuqori darajadagi matematik funktsiyalarning ulkan kutubxonasini taqdim etadi.</em>

<hr>
<hr style="height:3px;border-width:0;">

### What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

<h3>Uz:<em>  Python ro'yxati va NumPy massivi o'rtasidagi farq nima?</em></h3>
<em>NumPy sizga massivlarni yaratish va ulardagi raqamli ma'lumotlarni manipulyatsiya qilishning juda ko'p tez va samarali usullarini taqdim etadi. Python ro'yxati bitta ro'yxatda turli xil ma'lumotlar turlarini o'z ichiga olishi mumkin bo'lsa-da, NumPy massividagi barcha elementlar bir hil bo'lishi kerak. Agar massivlar bir hil bo'lmasa, massivlarda bajarilishi kerak bo'lgan matematik operatsiyalar juda samarasiz bo'lar edi.</em>
<h4><em>Nima uchun NumPy dan foydalanish kerak?</em></h4>
<em>NumPy massivlari Python ro'yxatlariga qaraganda tezroq va ixchamroq. Massiv kamroq xotira sarflaydi va ulardan foydalanish qulay. NumPy ma'lumotlarni saqlash uchun kamroq xotiradan foydalanadi va u ma'lumotlar turlarini belgilash mexanizmini ta'minlaydi. Bu kodni yanada optimallashtirish imkonini beradi.</em>>

<hr style="height:3.5px;border-width:0;">

<h3>What is an array?</h3>

An array is a central data structure of the NumPy library. 
An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array.
An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.
One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

<h3>Uz: Array (massiv) nima?</h3>
<em>Massiv NumPy kutubxonasining markaziy ma’lumotlar strukturasidir.
Massiv qiymatlar to'plami bo'lib, unda xom ma'lumotlar, elementni qanday topish va elementni qanday izohlash haqida ma'lumotlar mavjud. Unda turli yo'llar bilan indekslanishi mumkin bo'lgan elementlar to'plami mavjud. Elementlarning barchasi bir xil turdagi, massiv dtype deb ataladi.
Massiv manfiy bo'lmagan butun sonlar majmuasi, mantiqiy, boshqa massiv yoki butun sonlar bilan indekslanishi mumkin. Massivning darajasi - o'lchamlar soni. Massivning shakli har bir o'lcham bo'yicha massivning o'lchamini beruvchi butun sonlar majmuasidir.
NumPy massivlarini ishga tushirish usullaridan biri Python roʻyxatlaridan ikki yoki undan yuqori oʻlchamli maʼlumotlar uchun ichki roʻyxatlardan foydalanishdir.</em>.

<hr style="height:2.5px;border-width:0;">

* First we import <b>`numpy`</b>.  Most people `import` it <b>`as np`</b>. 

* Birinchi biz <b>`numpy`</b>ni import qilamiz. Ko'pchillik <b>`import numpy as np`</b> ko'rinishida yozishadi.

<hr style="height:2.5px;border-width:0;">

In [9]:
import numpy as np

## Creating arrays (Massivlar yaratish)


<img src="Images/numpy_arrays.png" align="center" width="400"/>

# `np.zeros`

### `Python NumPy zeros() Function`                      (Python Numpy nollar() Funksiyasi)

### `En` 
NumPy zeros() function is used to create a new array of given shapes and types filled with zero values. The zeros() function takes three arguments and returns the array filled with zeros of floating values by default. We can customize the specific datatype and order by passing these parameters.

### `Uz` 
NumPy zeros() funksiyasi nol qiymatlar bilan to'ldirilgan berilgan shakllar va turlarning yangi massivini yaratish uchun ishlatiladi. Zeros() funktsiyasi uchta argumentni oladi va sukut bo'yicha suzuvchi qiymatlarning nollari bilan to'ldirilgan massivni qaytaradi. Ushbu parametrlarni o'tkazish orqali biz ma'lum ma'lumotlar turini va tartibini sozlashimiz mumkin.

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


<hr style="height:2.5px;border-width:0;">

### `En` 
## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)
### `Uz` 
## Ba'zi lug'at

* NumPy-da har bir o'lcham **o'q** deb ataladi.
* O'qlar soni **darajali** deb ataladi.
     * Masalan, yuqoridagi 3x4 matritsa 2-darajali massivdir (u 2 o'lchovli).
     * Birinchi o'qning uzunligi 3, ikkinchisining uzunligi 4.
* Massivning oʻq uzunliklari roʻyxati massivning **shakli** deb ataladi.
     * Masalan, yuqoridagi matritsaning shakli `(3, 4)`.
     * Darajasi shakl uzunligiga teng.
* Massivning **oʻlchami** barcha oʻq uzunliklarining koʻpaytmasi boʻlgan elementlarning umumiy sonidir (masalan, 3*4=12)

<hr style="height:2.5px;border-width:0;">

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
<img src="np.zeros.png" align="center" width="300" />

In [12]:
a=np.zeros((1,6))

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<img src="Images/npzeros2.png" align="center" width="200" />

In [14]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

<img src="Images/npzeros3.png" align="center" width="200" />

In [15]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

<img src="Images/npzeros4.png" align="center" width="200" />

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

<img src="Images/npzeros3.png" align="center" width="200" />

# `np.ones`

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

<img src="Images/np.ones.png" align="center" width="500" />

In [18]:
a = np.zeros((5,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
a.shape

(5, 4)

In [20]:
a.dtype

dtype('float64')

In [21]:
a.ndim     # equal to len(a.shape)

2

In [22]:
a.size

20

<img src="Images/shapendim.jpg" align="center" width="500" />

<hr style="height:2.5px;border-width:0;">